### ISSUE TITLE
ValueError: Unknown split "train". Should be one of []

### ISSUE THREAD

**Issue by ZhiyuanChen** [google-research/vision_transformer#11]
Hi, 

Thank you for such a great work!

I was trying to run your code, but I have encountered the following error:

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/path/vit/vit_jax/input_pipeline.py", line 59, in get_dataset_info
    num_examples = data_builder.info.splits[split].num_examples
  File "/env/lib/python3.7/site-packages/tensorflow_datasets/core/splits.py", line 177, in __getitem__
    instruction=key,
  File "/env/lib/python3.7/site-packages/tensorflow_datasets/core/tfrecords_reader.py", line 99, in make_file_instructions
    absolute_instructions = instruction.to_absolute(name2len)
  File "/env/lib/python3.7/site-packages/tensorflow_datasets/core/tfrecords_reader.py", line 557, in to_absolute
    for rel_instr in self._relative_instructions]
  File "/env/lib/python3.7/site-packages/tensorflow_datasets/core/tfrecords_reader.py", line 557, in <listcomp>
    for rel_instr in self._relative_instructions]
  File "/env/lib/python3.7/site-packages/tensorflow_datasets/core/tfrecords_reader.py", line 384, in _rel_to_abs_instr
    split, list(name2len)))
ValueError: Unknown split "train". Should be one of []
```

I digged a little bit and found it looks like the `data_builder.info.splits` is an empty dict

![image](https://user-images.githubusercontent.com/28757366/97772863-e4e8e280-1b85-11eb-9fbc-3dc9ff9d1c42.png)

**Comment by akolesnikoff** [comment]
Did you follow the instructions from https://www.tensorflow.org/datasets/catalog/imagenet2012? In particular, you need to manually download ImageNet raw data and put it in the correct folder.

**Comment by ZhiyuanChen** [comment]
> Did you follow the instructions from https://www.tensorflow.org/datasets/catalog/imagenet2012? In particular, you need to manually download ImageNet raw data and put it in the correct folder.

Ahh, thanks for replying. I do have a decompressed copy of imagnet but it seems not recognising. I'm packaging it right now as instructed and I'll update how it works later.
